# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node: ['12']
    steps:
    - uses: actions/checkout@v2
#    - name: Danger
#      uses: danger/danger-js@10.6.4
    - name: Setup Node ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Install yarn
      run: npm install -g yarn
    - name: yarn install
      run: yarn install --frozen-lockfile
    - name: Danger JS
      run: yarn danger ci https://github.com/w-b-dev/try-dangerjs/pull/3
